"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from blog.settings.base import *
from blog.settings.database import *
from blog.settings.apps import *
from blog.settings.settings import *
